# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1231, 867)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_only_widget.setGeometry(QtCore.QRect(10, 20, 81, 831))
        self.icon_only_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_12.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_12.setSpacing(27)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(18, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 35, -1, -1)
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dashboardsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/dashboardsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_9.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/institutionsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/institutionsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(100, 16))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_9.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/studentssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/studentssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(100, 20))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_9.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.pushButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/teacherssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/teacherssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(100, 25))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_9.addWidget(self.pushButton_5)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.pushButton_7.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/financessmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icons/financessmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setIconSize(QtCore.QSize(100, 20))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_9.addWidget(self.pushButton_7)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        spacerItem2 = QtWidgets.QSpacerItem(20, 349, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.pushButton_8.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/settingssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/settingssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_8.setIcon(icon5)
        self.pushButton_8.setIconSize(QtCore.QSize(100, 20))
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_10.addWidget(self.pushButton_8)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/signoutsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/signoutsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(100, 16))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_10.addWidget(self.pushButton_6)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.icon_text_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_text_widget.setGeometry(QtCore.QRect(130, 20, 226, 831))
        self.icon_text_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
" color:white;\n"
"}\n"
"QPushButton{\n"
"  height:30px;\n"
"  border:none;\n"
"}")
        self.icon_text_widget.setObjectName("icon_text_widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.icon_text_widget)
        self.verticalLayout_11.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.icon_text_widget)
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.icon_text_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 50, -1, -1)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"padding-left:-60px\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.pushButton_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/dashboard2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/dashboard1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_2.setIcon(icon7)
        self.pushButton_2.setIconSize(QtCore.QSize(100, 16))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_7.addWidget(self.pushButton_2)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"padding-left:-65px\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.pushButton_9.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/institution2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/institution1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_9.setIcon(icon8)
        self.pushButton_9.setIconSize(QtCore.QSize(100, 45))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_7.addWidget(self.pushButton_9)
        self.students = QtWidgets.QFrame(parent=self.icon_text_widget)
        self.students.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.students.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.students.setObjectName("students")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.students)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.students)
        self.pushButton_10.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/students3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icons/students4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_10.setIcon(icon9)
        self.pushButton_10.setIconSize(QtCore.QSize(200, 60))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.students_dropdown = QtWidgets.QFrame(parent=self.students)
        self.students_dropdown.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.students_dropdown.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.students_dropdown.setObjectName("students_dropdown")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.students_dropdown)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout.addWidget(self.pushButton_17)
        self.verticalLayout_4.addWidget(self.students_dropdown)
        self.verticalLayout_7.addWidget(self.students)
        self.teachers = QtWidgets.QFrame(parent=self.icon_text_widget)
        self.teachers.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.teachers.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.teachers.setObjectName("teachers")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.teachers)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.teachers)
        self.pushButton_11.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/teachers3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon10.addPixmap(QtGui.QPixmap(":/icons/teachers4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_11.setIcon(icon10)
        self.pushButton_11.setIconSize(QtCore.QSize(200, 45))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_5.addWidget(self.pushButton_11)
        self.teachers_dropwdown = QtWidgets.QFrame(parent=self.teachers)
        self.teachers_dropwdown.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.teachers_dropwdown.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.teachers_dropwdown.setObjectName("teachers_dropwdown")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.teachers_dropwdown)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_24 = QtWidgets.QPushButton(parent=self.teachers_dropwdown)
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.pushButton_24.setCheckable(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_2.addWidget(self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(parent=self.teachers_dropwdown)
        self.pushButton_25.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.pushButton_25.setCheckable(True)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_2.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(parent=self.teachers_dropwdown)
        self.pushButton_26.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.pushButton_26.setCheckable(True)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_2.addWidget(self.pushButton_26)
        self.verticalLayout_5.addWidget(self.teachers_dropwdown)
        self.verticalLayout_7.addWidget(self.teachers)
        self.finances = QtWidgets.QFrame(parent=self.icon_text_widget)
        self.finances.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.finances.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.finances.setObjectName("finances")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.finances)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.finances)
        self.pushButton_12.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/finances3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_12.setIcon(icon11)
        self.pushButton_12.setIconSize(QtCore.QSize(200, 45))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_6.addWidget(self.pushButton_12)
        self.finances_dropdown = QtWidgets.QFrame(parent=self.finances)
        self.finances_dropdown.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.finances_dropdown.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.finances_dropdown.setObjectName("finances_dropdown")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.finances_dropdown)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_27 = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.pushButton_27.setCheckable(True)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_3.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.pushButton_28.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.pushButton_28.setCheckable(True)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_3.addWidget(self.pushButton_28)
        self.pushButton_29 = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.pushButton_29.setCheckable(True)
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_3.addWidget(self.pushButton_29)
        self.verticalLayout_6.addWidget(self.finances_dropdown)
        self.verticalLayout_7.addWidget(self.finances)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(18, 48, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"padding-left:-65px\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.pushButton_13.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/settings2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon12.addPixmap(QtGui.QPixmap(":/icons/settings1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_13.setIcon(icon12)
        self.pushButton_13.setIconSize(QtCore.QSize(200, 45))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_8.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"padding-left:-60px\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.pushButton_14.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/signout2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon13.addPixmap(QtGui.QPixmap(":/icons/signout1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_14.setIcon(icon13)
        self.pushButton_14.setIconSize(QtCore.QSize(100, 16))
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_8.addWidget(self.pushButton_14)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.main_screen_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.main_screen_widget.setGeometry(QtCore.QRect(360, 130, 841, 721))
        self.main_screen_widget.setStyleSheet("background-color: rgb(131, 255, 189);")
        self.main_screen_widget.setObjectName("main_screen_widget")
        self.widget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(360, 20, 841, 91))
        self.widget_4.setObjectName("widget_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_10.toggled['bool'].connect(self.students_dropdown.hide) # type: ignore
        self.pushButton_11.toggled['bool'].connect(self.teachers_dropwdown.setHidden) # type: ignore
        self.pushButton_12.toggled['bool'].connect(self.finances_dropdown.setHidden) # type: ignore
        self.pushButton_10.toggled['bool'].connect(self.students_dropdown.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "WATER QA"))
        self.pushButton_15.setText(_translate("MainWindow", "Sub_Menu_1"))
        self.pushButton_16.setText(_translate("MainWindow", "Sub_Menu_2"))
        self.pushButton_17.setText(_translate("MainWindow", "Sub_Menu_3"))
        self.pushButton_24.setText(_translate("MainWindow", "Sub_Menu_1"))
        self.pushButton_25.setText(_translate("MainWindow", "Sub_Menu_2"))
        self.pushButton_26.setText(_translate("MainWindow", "Sub_Menu_3"))
        self.pushButton_27.setText(_translate("MainWindow", "Sub_Menu_1"))
        self.pushButton_28.setText(_translate("MainWindow", "Sub_Menu_2"))
        self.pushButton_29.setText(_translate("MainWindow", "Sub_Menu_3"))
