# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1255, 888)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 29, 1211, 821))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.widget)
        self.icon_only_widget.setMinimumSize(QtCore.QSize(71, 0))
        self.icon_only_widget.setMaximumSize(QtCore.QSize(71, 16777215))
        self.icon_only_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_12.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_12.setSpacing(27)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(18, 18, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 35, -1, -1)
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.dashboard_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.dashboard_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dashboardsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/dashboardsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.dashboard_1.setIcon(icon)
        self.dashboard_1.setIconSize(QtCore.QSize(20, 20))
        self.dashboard_1.setCheckable(True)
        self.dashboard_1.setAutoExclusive(True)
        self.dashboard_1.setObjectName("dashboard_1")
        self.verticalLayout_9.addWidget(self.dashboard_1)
        self.institution_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.institution_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/institutionsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/institutionsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.institution_1.setIcon(icon1)
        self.institution_1.setIconSize(QtCore.QSize(100, 16))
        self.institution_1.setCheckable(True)
        self.institution_1.setAutoExclusive(True)
        self.institution_1.setObjectName("institution_1")
        self.verticalLayout_9.addWidget(self.institution_1)
        self.students_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.students_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/studentssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/studentssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.students_1.setIcon(icon2)
        self.students_1.setIconSize(QtCore.QSize(100, 20))
        self.students_1.setCheckable(True)
        self.students_1.setAutoExclusive(True)
        self.students_1.setObjectName("students_1")
        self.verticalLayout_9.addWidget(self.students_1)
        self.teachers_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.teachers_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/teacherssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/teacherssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.teachers_1.setIcon(icon3)
        self.teachers_1.setIconSize(QtCore.QSize(100, 25))
        self.teachers_1.setCheckable(True)
        self.teachers_1.setAutoExclusive(True)
        self.teachers_1.setObjectName("teachers_1")
        self.verticalLayout_9.addWidget(self.teachers_1)
        self.binance_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.binance_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/financessmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icons/financessmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.binance_1.setIcon(icon4)
        self.binance_1.setIconSize(QtCore.QSize(100, 20))
        self.binance_1.setCheckable(True)
        self.binance_1.setAutoExclusive(True)
        self.binance_1.setObjectName("binance_1")
        self.verticalLayout_9.addWidget(self.binance_1)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        spacerItem2 = QtWidgets.QSpacerItem(20, 335, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.settings_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.settings_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/settingssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/settingssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.settings_1.setIcon(icon5)
        self.settings_1.setIconSize(QtCore.QSize(100, 20))
        self.settings_1.setCheckable(True)
        self.settings_1.setAutoExclusive(True)
        self.settings_1.setObjectName("settings_1")
        self.verticalLayout_10.addWidget(self.settings_1)
        self.log_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.log_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/signoutsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/signoutsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.log_1.setIcon(icon6)
        self.log_1.setIconSize(QtCore.QSize(100, 16))
        self.log_1.setCheckable(True)
        self.log_1.setAutoExclusive(True)
        self.log_1.setObjectName("log_1")
        self.verticalLayout_10.addWidget(self.log_1)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.icon_text_widget = QtWidgets.QWidget(parent=self.widget)
        self.icon_text_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
" color:white;\n"
"}\n"
"QPushButton{\n"
"  height:30px;\n"
"  border:none;\n"
"}")
        self.icon_text_widget.setObjectName("icon_text_widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.icon_text_widget)
        self.verticalLayout_11.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(15, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.icon_text_widget)
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.icon_text_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 50, -1, -1)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.dashboard_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.dashboard_2.setStyleSheet("QPushButton{\n"
"padding-left:-60px\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.dashboard_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/dashboard2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/dashboard1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.dashboard_2.setIcon(icon7)
        self.dashboard_2.setIconSize(QtCore.QSize(100, 16))
        self.dashboard_2.setCheckable(True)
        self.dashboard_2.setObjectName("dashboard_2")
        self.verticalLayout_7.addWidget(self.dashboard_2)
        self.institution_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.institution_2.setStyleSheet("QPushButton{\n"
"padding-left:-65px\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.institution_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/institution2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/institution1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.institution_2.setIcon(icon8)
        self.institution_2.setIconSize(QtCore.QSize(100, 45))
        self.institution_2.setCheckable(True)
        self.institution_2.setObjectName("institution_2")
        self.verticalLayout_7.addWidget(self.institution_2)
        self.students = QtWidgets.QFrame(parent=self.icon_text_widget)
        self.students.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.students.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.students.setObjectName("students")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.students)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.students_2 = QtWidgets.QPushButton(parent=self.students)
        self.students_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/students3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icons/students4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.students_2.setIcon(icon9)
        self.students_2.setIconSize(QtCore.QSize(200, 60))
        self.students_2.setCheckable(True)
        self.students_2.setObjectName("students_2")
        self.verticalLayout_4.addWidget(self.students_2)
        self.students_dropdown = QtWidgets.QFrame(parent=self.students)
        self.students_dropdown.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.students_dropdown.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.students_dropdown.setObjectName("students_dropdown")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.students_dropdown)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sub_menu_1 = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.sub_menu_1.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.sub_menu_1.setCheckable(True)
        self.sub_menu_1.setObjectName("sub_menu_1")
        self.verticalLayout.addWidget(self.sub_menu_1)
        self.sub_menu_2 = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.sub_menu_2.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.sub_menu_2.setCheckable(True)
        self.sub_menu_2.setObjectName("sub_menu_2")
        self.verticalLayout.addWidget(self.sub_menu_2)
        self.sub_menu_3 = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.sub_menu_3.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.sub_menu_3.setCheckable(True)
        self.sub_menu_3.setObjectName("sub_menu_3")
        self.verticalLayout.addWidget(self.sub_menu_3)
        self.verticalLayout_4.addWidget(self.students_dropdown)
        self.verticalLayout_7.addWidget(self.students)
        self.teachers = QtWidgets.QFrame(parent=self.icon_text_widget)
        self.teachers.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.teachers.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.teachers.setObjectName("teachers")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.teachers)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.teachers_2 = QtWidgets.QPushButton(parent=self.teachers)
        self.teachers_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/teachers3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon10.addPixmap(QtGui.QPixmap(":/icons/teachers4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.teachers_2.setIcon(icon10)
        self.teachers_2.setIconSize(QtCore.QSize(200, 45))
        self.teachers_2.setCheckable(True)
        self.teachers_2.setObjectName("teachers_2")
        self.verticalLayout_5.addWidget(self.teachers_2)
        self.teachers_dropwdown = QtWidgets.QFrame(parent=self.teachers)
        self.teachers_dropwdown.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.teachers_dropwdown.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.teachers_dropwdown.setObjectName("teachers_dropwdown")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.teachers_dropwdown)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sub_menu_4 = QtWidgets.QPushButton(parent=self.teachers_dropwdown)
        self.sub_menu_4.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.sub_menu_4.setCheckable(True)
        self.sub_menu_4.setObjectName("sub_menu_4")
        self.verticalLayout_2.addWidget(self.sub_menu_4)
        self.sub_menu_5 = QtWidgets.QPushButton(parent=self.teachers_dropwdown)
        self.sub_menu_5.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.sub_menu_5.setCheckable(True)
        self.sub_menu_5.setObjectName("sub_menu_5")
        self.verticalLayout_2.addWidget(self.sub_menu_5)
        self.sub_menu_6 = QtWidgets.QPushButton(parent=self.teachers_dropwdown)
        self.sub_menu_6.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.sub_menu_6.setCheckable(True)
        self.sub_menu_6.setObjectName("sub_menu_6")
        self.verticalLayout_2.addWidget(self.sub_menu_6)
        self.verticalLayout_5.addWidget(self.teachers_dropwdown)
        self.verticalLayout_7.addWidget(self.teachers)
        self.finances = QtWidgets.QFrame(parent=self.icon_text_widget)
        self.finances.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.finances.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.finances.setObjectName("finances")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.finances)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.binance_2 = QtWidgets.QPushButton(parent=self.finances)
        self.binance_2.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/finances3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.binance_2.setIcon(icon11)
        self.binance_2.setIconSize(QtCore.QSize(200, 45))
        self.binance_2.setCheckable(True)
        self.binance_2.setObjectName("binance_2")
        self.verticalLayout_6.addWidget(self.binance_2)
        self.finances_dropdown = QtWidgets.QFrame(parent=self.finances)
        self.finances_dropdown.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.finances_dropdown.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.finances_dropdown.setObjectName("finances_dropdown")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.finances_dropdown)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sub_menu_7 = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.sub_menu_7.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.sub_menu_7.setCheckable(True)
        self.sub_menu_7.setObjectName("sub_menu_7")
        self.verticalLayout_3.addWidget(self.sub_menu_7)
        self.sub_menu_8 = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.sub_menu_8.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.sub_menu_8.setCheckable(True)
        self.sub_menu_8.setObjectName("sub_menu_8")
        self.verticalLayout_3.addWidget(self.sub_menu_8)
        self.pushButton_29 = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"padding-left:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.pushButton_29.setCheckable(True)
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_3.addWidget(self.pushButton_29)
        self.verticalLayout_6.addWidget(self.finances_dropdown)
        self.verticalLayout_7.addWidget(self.finances)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(18, 39, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.settings_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.settings_2.setStyleSheet("QPushButton{\n"
"padding-left:-65px\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.settings_2.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/settings2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon12.addPixmap(QtGui.QPixmap(":/icons/settings1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.settings_2.setIcon(icon12)
        self.settings_2.setIconSize(QtCore.QSize(200, 45))
        self.settings_2.setCheckable(True)
        self.settings_2.setObjectName("settings_2")
        self.verticalLayout_8.addWidget(self.settings_2)
        self.log_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.log_2.setStyleSheet("QPushButton{\n"
"padding-left:-60px\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.log_2.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/signout2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon13.addPixmap(QtGui.QPixmap(":/icons/signout1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.log_2.setIcon(icon13)
        self.log_2.setIconSize(QtCore.QSize(100, 16))
        self.log_2.setCheckable(True)
        self.log_2.setObjectName("log_2")
        self.verticalLayout_8.addWidget(self.log_2)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.gridLayout.addWidget(self.icon_text_widget, 0, 1, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton.setStyleSheet("border:none;")
        self.pushButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon14)
        self.pushButton.setIconSize(QtCore.QSize(29, 29))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label = QtWidgets.QLabel(parent=self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_13.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(563, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_6 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_6.setMaximumSize(QtCore.QSize(50, 50))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/profile.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_14.addWidget(self.widget_4)
        self.main_screen_widget = QtWidgets.QWidget(parent=self.widget)
        self.main_screen_widget.setMinimumSize(QtCore.QSize(841, 741))
        self.main_screen_widget.setMaximumSize(QtCore.QSize(920, 741))
        self.main_screen_widget.setStyleSheet("")
        self.main_screen_widget.setObjectName("main_screen_widget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_screen_widget)
        self.stackedWidget.setGeometry(QtCore.QRect(60, 0, 800, 741))
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 741))
        self.stackedWidget.setMaximumSize(QtCore.QSize(800, 741))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_7 = QtWidgets.QLabel(parent=self.page)
        self.label_7.setGeometry(QtCore.QRect(300, 290, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_8 = QtWidgets.QLabel(parent=self.page_2)
        self.label_8.setGeometry(QtCore.QRect(320, 290, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_9 = QtWidgets.QLabel(parent=self.page_3)
        self.label_9.setGeometry(QtCore.QRect(310, 300, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_10 = QtWidgets.QLabel(parent=self.page_4)
        self.label_10.setGeometry(QtCore.QRect(280, 330, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_14.addWidget(self.main_screen_widget)
        self.gridLayout.addLayout(self.verticalLayout_14, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.students_2.toggled['bool'].connect(self.students_dropdown.hide) # type: ignore
        self.teachers_2.toggled['bool'].connect(self.teachers_dropwdown.setHidden) # type: ignore
        self.binance_2.toggled['bool'].connect(self.finances_dropdown.setHidden) # type: ignore
        self.students_2.toggled['bool'].connect(self.students_dropdown.setHidden) # type: ignore
        self.dashboard_2.toggled['bool'].connect(self.dashboard_1.setChecked) # type: ignore
        self.institution_2.toggled['bool'].connect(self.institution_1.setChecked) # type: ignore
        self.students_2.toggled['bool'].connect(self.students_1.setChecked) # type: ignore
        self.teachers_2.toggled['bool'].connect(self.teachers_1.setChecked) # type: ignore
        self.binance_2.toggled['bool'].connect(self.binance_1.setChecked) # type: ignore
        self.settings_2.toggled['bool'].connect(self.settings_1.setChecked) # type: ignore
        self.log_2.toggled['bool'].connect(self.log_1.setChecked) # type: ignore
        self.log_1.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.log_2.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.pushButton.toggled['bool'].connect(self.icon_text_widget.setHidden) # type: ignore
        self.pushButton.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "WATER QA"))
        self.sub_menu_1.setText(_translate("MainWindow", "Sub_Menu_1"))
        self.sub_menu_2.setText(_translate("MainWindow", "Sub_Menu_2"))
        self.sub_menu_3.setText(_translate("MainWindow", "Sub_Menu_3"))
        self.sub_menu_4.setText(_translate("MainWindow", "Sub_Menu_1"))
        self.sub_menu_5.setText(_translate("MainWindow", "Sub_Menu_2"))
        self.sub_menu_6.setText(_translate("MainWindow", "Sub_Menu_3"))
        self.sub_menu_7.setText(_translate("MainWindow", "Sub_Menu_1"))
        self.sub_menu_8.setText(_translate("MainWindow", "Sub_Menu_2"))
        self.pushButton_29.setText(_translate("MainWindow", "Sub_Menu_3"))
        self.label.setText(_translate("MainWindow", "HOLA DE NUEVO"))
        self.label_5.setText(_translate("MainWindow", "MESSAGE"))
        self.label_7.setText(_translate("MainWindow", "DASHBOARD"))
        self.label_8.setText(_translate("MainWindow", "SIDE_MENU_2"))
        self.label_9.setText(_translate("MainWindow", "SUB_MENU_2"))
        self.label_10.setText(_translate("MainWindow", "SUB_MENU_3"))
